### ISSUE TITLE
Rounded corner for Image not working

### ISSUE THREAD

**Issue by c-villain** [kyleve/Listable#214]
.box(corners: .rounded(radius: 15.0)) not make rounded Image

**Comment by kyleve** [comment]
I think you might want to file this in Blueprint? Though it's more than likely you just need to set `clipsContent` to true: https://github.com/square/Blueprint/blob/main/BlueprintUICommonControls/Sources/Box.swift#L22

**Comment by c-villain** [comment]
Yeap, its work! 🤟🏻
