### ISSUE TITLE
add .carousel in LayoutDescription

### ISSUE THREAD

**Issue by c-villain** [kyleve/Listable#218]
for example  row.layout = .carousel {..} with vertical and horizontal scrolling
or .list { $0.direction = .horizontal }

![IMG_5196](https://user-images.githubusercontent.com/6235615/99155001-57e57380-26c5-11eb-9681-914b4efd9112.jpg)

**Comment by kyleve** [comment]
This is probably something that should be added to the `.paged` option; though I'm not 100% sure how to control the scroll paging like this.

**Comment by kyleve** [comment]
Check out the new `.pagingBehavior` on `.table` and `.flow`: https://github.com/kyleve/Listable/pull/359
